---

# see: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/template_module.html
- name: put hello text file
  template:
    src: hello.txt.j2
    dest: /root/hello.txt
    mode: 0644
    owner: root
    group: root
